<?php
	namespace App\Http\Controllers\Api\Aggregate;

	use App\Http\Controllers\Controller;
	use DB;

	class Gener43_2021_core_test extends Controller
	{
		
		public function gener43_2021_core_test_create(){
			$data = array(
				"_URI" => Request::input("_uri"),
"_CREATOR_URI_USER" => Request::input("_creator_uri_user"),
"_CREATION_DATE" => Request::input("_creation_date"),
"_LAST_UPDATE_URI_USER" => Request::input("_last_update_uri_user"),
"_LAST_UPDATE_DATE" => Request::input("_last_update_date"),
"_MODEL_VERSION" => Request::input("_model_version"),
"_UI_VERSION" => Request::input("_ui_version"),
"_IS_COMPLETE" => Request::input("_is_complete"),
"_SUBMISSION_DATE" => Request::input("_submission_date"),
"_MARKED_AS_COMPLETE_DATE" => Request::input("_marked_as_complete_date"),
"LAND_STATISTICS_BEAT_LAND_BIO_OTHER_PLANT_HA" => Request::input("land_statistics_beat_land_bio_other_plant_ha"),
"GUSER_TLOC_FD_BEAT_POINT_LNG" => Request::input("guser_tloc_fd_beat_point_lng"),
"FBLI_FA_TLOC_FD_BEAT" => Request::input("fbli_fa_tloc_fd_beat"),
"LOGISTICS3_COUNTRYBOAT_CONDITION" => Request::input("logistics3_countryboat_condition"),
"LOGISTICS4_GFIREARMS_303RIFLE" => Request::input("logistics4_gfirearms_303rifle"),
"LAND_STATISTICS_BEAT_MGT_APPROACH_OTHER_PA_AREA_HA" => Request::input("land_statistics_beat_mgt_approach_other_pa_area_ha"),
"LOGISTICS4_OTHERS_WATER_TRA" => Request::input("logistics4_others_water_tra"),
"BO_INFO_BO_CELL" => Request::input("bo_info_bo_cell"),
"LOGISTICS3_TVESSEL_CONDITION" => Request::input("logistics3_tvessel_condition"),
"RO_INFO_RO_CELL" => Request::input("ro_info_ro_cell"),
"LOGISTICS4_TFIREARMS_CHINESERIFLE_AVAIL" => Request::input("logistics4_tfirearms_chineserifle_avail"),
"LOGISTICS3_TVESSEL_AVAIL" => Request::input("logistics3_tvessel_avail"),
"FBLI_FA_TLOC_FD_BEAT_TXT" => Request::input("fbli_fa_tloc_fd_beat_txt"),
"LOGISTICS3_SPEEDBOAT_CONDITION" => Request::input("logistics3_speedboat_condition"),
"FBLI_FA_TLOC_FD_DIVISION" => Request::input("fbli_fa_tloc_fd_division"),
"LAND_TRANSPORTS_BICYCLE_AVAIL" => Request::input("land_transports_bicycle_avail"),
"LOGISTICS3_OTHERS_WATER_TRA_CONDITION" => Request::input("logistics3_others_water_tra_condition"),
"LAND_STATISTICS_BEAT_LAND_INFO_VESTED_FOREST_HA" => Request::input("land_statistics_beat_land_info_vested_forest_ha"),
"SUBSCRIBERID" => Request::input("subscriberid"),
"GUSER_USER" => Request::input("guser_user"),
"RO_INFO_NAME_OF_RO" => Request::input("ro_info_name_of_ro"),
"FBLI_FA_TLOC_FD_BLOCK" => Request::input("fbli_fa_tloc_fd_block"),
"DEVICEID" => Request::input("deviceid"),
"LAND_TRANSPORTS_MOTORB_CONDITION" => Request::input("land_transports_motorb_condition"),
"FBLI_GENERATED_NOTE_NAME_18" => Request::input("fbli_generated_note_name_18"),
"LAND_STATISTICS_BEAT_LAND_BIO_GENERATED_NOTE_NAME_74" => Request::input("land_statistics_beat_land_bio_generated_note_name_74"),
"LOGISTICS4_CHINESERIFLE_CONDITION" => Request::input("logistics4_chineserifle_condition"),
"LOGISTICS3_SPEEDBOAT_AVAIL" => Request::input("logistics3_speedboat_avail"),
"LAND_STATISTICS_BEAT_MGT_APPROACH_PA_WS_HA" => Request::input("land_statistics_beat_mgt_approach_pa_ws_ha"),
"LOGISTICS4_GENERATED_NOTE_NAME_152" => Request::input("logistics4_generated_note_name_152"),
"LAND_STATISTICS_BEAT_LAND_BIO_NON_PP_HA" => Request::input("land_statistics_beat_land_bio_non_pp_ha"),
"LAND_STATISTICS_BEAT_LAND_INFO_SECTION_6_HA" => Request::input("land_statistics_beat_land_info_section_6_ha"),
"SIMSERIAL" => Request::input("simserial"),
"GUSER_DCOLLECTION_RAW" => Request::input("guser_dcollection_raw"),
"LAND_TRANSPORTS_BICYCLE_CONDITION" => Request::input("land_transports_bicycle_condition"),
"LAND_STATISTICS_BEAT_LAND_BIO_SOCIAL_ACCRETED_HA" => Request::input("land_statistics_beat_land_bio_social_accreted_ha"),
"GUSER_GENERATED_NOTE_NAME_10" => Request::input("guser_generated_note_name_10"),
"LAND_STATISTICS_BEAT_LAND_INFO_OTHER_FORESTAREA_HA" => Request::input("land_statistics_beat_land_info_other_forestarea_ha"),
"BO_INFO_BO_NID" => Request::input("bo_info_bo_nid"),
"LAND_TRANSPORTS_GBI_CYCLE" => Request::input("land_transports_gbi_cycle"),
"LAND_TRANSPORTS_OTHERS_LAND_TRA" => Request::input("land_transports_others_land_tra"),
"LOGISTICS3_GCOUNTRY_BOAT" => Request::input("logistics3_gcountry_boat"),
"LOGISTICS4_GFIREARMS_SLR" => Request::input("logistics4_gfirearms_slr"),
"FBLI_FA_TLOC_FD_CIR" => Request::input("fbli_fa_tloc_fd_cir"),
"LAND_TRANSPORTS_MOTORB_AVAIL" => Request::input("land_transports_motorb_avail"),
"LAND_TRANSPORTS_OTHERS_LAND_TRA_CONDITION" => Request::input("land_transports_others_land_tra_condition"),
"RO_INFO_RO_JOINING_DATE" => Request::input("ro_info_ro_joining_date"),
"LOGISTICS4_OTHERS_WATER_TRA_CONDITION" => Request::input("logistics4_others_water_tra_condition"),
"LAND_STATISTICS_BEAT_LAND_BIO_NATURAL_TO_DC_HA" => Request::input("land_statistics_beat_land_bio_natural_to_dc_ha"),
"RO_INFO_RO_RANK" => Request::input("ro_info_ro_rank"),
"LAND_TRANSPORTS_OTHERS_LAND_TRA_AVAIL" => Request::input("land_transports_others_land_tra_avail"),
"LAND_STATISTICS_BEAT_MGT_APPROACH_PA_SAFARIPARK_HA" => Request::input("land_statistics_beat_mgt_approach_pa_safaripark_ha"),
"BO_INFO_BO_JOINING_DATE" => Request::input("bo_info_bo_joining_date"),
"GUSER_USER_CELL" => Request::input("guser_user_cell"),
"RO_INFO_RO_NID" => Request::input("ro_info_ro_nid"),
"GUSER_TLOC_FD_BEAT_POINT_ALT" => Request::input("guser_tloc_fd_beat_point_alt"),
"LAND_STATISTICS_BEAT_LAND_INFO_SECTION_4_HA" => Request::input("land_statistics_beat_land_info_section_4_ha"),
"GUSER_TLOC_FD_BEAT_POINT_LAT" => Request::input("guser_tloc_fd_beat_point_lat"),
"LAND_STATISTICS_BEAT_MGT_APPROACH_PA_SBCA_HA" => Request::input("land_statistics_beat_mgt_approach_pa_sbca_ha"),
"LOGISTICS4_RIFLE303_CONDITION" => Request::input("logistics4_rifle303_condition"),
"GUSER_DCOLLECTION" => Request::input("guser_dcollection"),
"END_RAW" => Request::input("end_raw"),
"BO_INFO_GENERATED_NOTE_NAME_106" => Request::input("bo_info_generated_note_name_106"),
"GENERATED_NOTE_NAME_81" => Request::input("generated_note_name_81"),
"RO_INFO_GENERATED_NOTE_NAME_97" => Request::input("ro_info_generated_note_name_97"),
"FBLI_FA_GENERATED_NOTE_NAME_21" => Request::input("fbli_fa_generated_note_name_21"),
"LAND_TRANSPORTS_GENERATED_NOTE_NAME_125" => Request::input("land_transports_generated_note_name_125"),
"GUSER_BEAT_ADDRESS" => Request::input("guser_beat_address"),
"LAND_STATISTICS_BEAT_LAND_INFO_AQUIRED_FOREST_HA" => Request::input("land_statistics_beat_land_info_aquired_forest_ha"),
"BO_INFO_BO_JOINING_DATE_RAW" => Request::input("bo_info_bo_joining_date_raw"),
"LAND_STATISTICS_BEAT_MGT_APPROACH_PA_NP_HA" => Request::input("land_statistics_beat_mgt_approach_pa_np_ha"),
"GUSER_TLOC_FD_BEAT_POINT_ACC" => Request::input("guser_tloc_fd_beat_point_acc"),
"LOGISTICS3_COUNTRYBOAT_AVAIL" => Request::input("logistics3_countryboat_avail"),
"FBLI_CA_TLOC_AD_DISTRICT" => Request::input("fbli_ca_tloc_ad_district"),
"BO_INFO_NAME_OF_BO" => Request::input("bo_info_name_of_bo"),
"LAND_STATISTICS_BEAT_LAND_INFO_GENERATED_NOTE_NAME_53" => Request::input("land_statistics_beat_land_info_generated_note_name_53"),
"LAND_STATISTICS_BEAT_LAND_INFO_RESERVED_FOREST_HA" => Request::input("land_statistics_beat_land_info_reserved_forest_ha"),
"LOGISTICS3_OTHERS_WATER_TRA" => Request::input("logistics3_others_water_tra"),
"FBLI_TLOC_ECOZONE" => Request::input("fbli_tloc_ecozone"),
"BO_INFO_BO_RANK" => Request::input("bo_info_bo_rank"),
"LOGISTICS4_SLR_CONDITION" => Request::input("logistics4_slr_condition"),
"END" => Request::input("end"),
"FBLI_FA_TLOC_FD_RANGE" => Request::input("fbli_fa_tloc_fd_range"),
"RO_INFO_RO_JOINING_DATE_RAW" => Request::input("ro_info_ro_joining_date_raw"),
"PHONENUMBER" => Request::input("phonenumber"),
"LOGISTICS3_TRAWLER" => Request::input("logistics3_trawler"),
"LOGISTICS4_GFIREARMS_SHORTGUN" => Request::input("logistics4_gfirearms_shortgun"),
"LOGISTICS4_SHORTGUN_CONDITION" => Request::input("logistics4_shortgun_condition"),
"START_RAW" => Request::input("start_raw"),
"LAND_STATISTICS_TOTAL_LEGAL_LAND_STATS" => Request::input("land_statistics_total_legal_land_stats"),
"BO_INFO_BO_MAIL" => Request::input("bo_info_bo_mail"),
"META_INSTANCE_ID" => Request::input("meta_instance_id"),
"LOGISTICS4_TFIREARMS_SHORTGUN_AVAIL" => Request::input("logistics4_tfirearms_shortgun_avail"),
"FBLI_CA_GENERATED_NOTE_NAME_33" => Request::input("fbli_ca_generated_note_name_33"),
"FBLI_CA_TLOC_AD_DIVISION" => Request::input("fbli_ca_tloc_ad_division"),
"LAND_STATISTICS_BEAT_MGT_APPROACH_GENERATED_NOTE_NAME_65" => Request::input("land_statistics_beat_mgt_approach_generated_note_name_65"),
"LOGISTICS4_OTHERS_WATER_TRA_AVAIL" => Request::input("logistics4_others_water_tra_avail"),
"LOGISTICS3_GSPEED_BOAT" => Request::input("logistics3_gspeed_boat"),
"LOGISTICS4_TFIREARMS_303RIFLE_AVAIL" => Request::input("logistics4_tfirearms_303rifle_avail"),
"LOGISTICS4_GFIREARMS_CHINESERIFLE" => Request::input("logistics4_gfirearms_chineserifle"),
"TODAY" => Request::input("today"),
"FBLI_FA_TLOC_FD_CHAR" => Request::input("fbli_fa_tloc_fd_char"),
"LAND_TRANSPORTS_GMOTORBIKE" => Request::input("land_transports_gmotorbike"),
"LAND_STATISTICS_BEAT_LAND_INFO_PROTECTED_FOREST_HA" => Request::input("land_statistics_beat_land_info_protected_forest_ha"),
"LAND_STATISTICS_BEAT_MGT_APPROACH_PA_ECOPARK_HA" => Request::input("land_statistics_beat_mgt_approach_pa_ecopark_ha"),
"FBLI_FA_TLOC_ENTER_RANGE" => Request::input("fbli_fa_tloc_enter_range"),
"LAND_STATISTICS_AREA_SUM" => Request::input("land_statistics_area_sum"),
"RO_INFO_RO_MAIL" => Request::input("ro_info_ro_mail"),
"GENERATED_NOTE_NAME_123" => Request::input("generated_note_name_123"),
"START" => Request::input("start"),
"FBLI_CA_UNION" => Request::input("fbli_ca_union"),
"FBLI_FA_TLOC_ENTER_DIV" => Request::input("fbli_fa_tloc_enter_div"),
"TODAY_RAW" => Request::input("today_raw"),
"GENERATED_NOTE_NAME_94" => Request::input("generated_note_name_94"),
"LOGISTICS3_OTHERS_WATER_TRA_AVAIL" => Request::input("logistics3_others_water_tra_avail"),
"GENERATED_NOTE_NAME_95" => Request::input("generated_note_name_95"),
"LOGISTICS4_TFIREARMS_SLR_AVAIL" => Request::input("logistics4_tfirearms_slr_avail"),
"LOGISTICS3_GENERATED_NOTE_NAME_137" => Request::input("logistics3_generated_note_name_137"),
"project_id" => Request::input("project_id"),
"sort" => Request::input("sort"),
"last_log_id" => Request::input("last_log_id"),
"restore_id" => Request::input("restore_id"),
"created_at" => Request::input("created_at"),
"created_by" => Request::input("created_by"),
"updated_at" => Request::input("updated_at"),
"updated_by" => Request::input("updated_by"),
"deleted_at" => Request::input("deleted_at"),
"deleted_by" => Request::input("deleted_by"),
"deleted_status" => Request::input("deleted_status"),
"status" => Request::input("status"),

			);
			$insert_id = DB::table("GENER43_2021_CORE_TEST")->insertGetId($data);
			return response()->json($insert_id);
		}
		public function gener43_2021_core_test_list(){
			$query = DB::select('select * from aggregate."GENER43_2021_CORE_TEST"');
			return response()->json($query);
		}
	}
			