<?php
	namespace App\Http\Controllers\Api\Aggregate;

	use App\Http\Controllers\Controller;
	use DB;
	use Illuminate\Http\Request;
	class Plant27_2021_core extends Controller
	{
		
		public function plant27_2021_core_create(Request $request){
			$data = array(
				"_URI" => $request->post("_uri"),
							"_CREATOR_URI_USER" => $request->post("_creator_uri_user"),
							"_CREATION_DATE" => $request->post("_creation_date"),							
							"_LAST_UPDATE_DATE" => $request->post("_last_update_date"),
							// "_MODEL_VERSION" => $request->post("_model_version"),
							// "_UI_VERSION" => $request->post("_ui_version"),
							// "_IS_COMPLETE" => $request->post("_is_complete"),
							// "_SUBMISSION_DATE" => $request->post("_submission_date"),
							// "_MARKED_AS_COMPLETE_DATE" => $request->post("_marked_as_complete_date"),
							// "PLANTING_PLAN_SEEDLING_NUM_GENERATED_NOTE_NAME_173" => $request->post("planting_plan_seedling_num_generated_note_name_173"),
							// "REG_AVG_SEEDLING_ALL_PLOTS" => $request->post("reg_avg_seedling_all_plots"),
							// "PLANTING_PLAN_GRPSTOCKS_NTE_1" => $request->post("planting_plan_grpstocks_nte_1"),
							// "PLANTING_PLAN_GRPSTOCKS_NTE_2" => $request->post("planting_plan_grpstocks_nte_2"),
							// "PLANTING_PLAN_SEEDLING_NUM_GENERATED_NOTE_NAME_174" => $request->post("planting_plan_seedling_num_generated_note_name_174"),
							// "LOCATION_DATA_CA_TLOC_AD_DISTRICT" => $request->post("location_data_ca_tloc_ad_district"),
							// "MAGROVE_PLANT_WIND_DIR" => $request->post("magrove_plant_wind_dir"),
							// "GSITE_HISTORY" => $request->post("gsite_history"),
							// "LOCATION_DATA_GENERATED_NOTE_NAME_20" => $request->post("location_data_generated_note_name_20"),
							// "GTRTS_PLANTING_PLANTING_YEAR" => $request->post("gtrts_planting_planting_year"),
							// "INTERVENTION_DETAILS_PATCHES_PLANT" => $request->post("intervention_details_patches_plant"),
							// "INTERVENTION_DETAILS_SEEDING_PLANT" => $request->post("intervention_details_seeding_plant"),
							// "PLANTING_PLAN_GPLANTING_SPACING" => $request->post("planting_plan_gplanting_spacing"),
							// "MAGROVE_PLANT_MAN_AFF_CLAY_LAYER" => $request->post("magrove_plant_man_aff_clay_layer"),
							// "GTRTS_OTHER_TREATMENT_OTHER_YEAR" => $request->post("gtrts_other_treatment_other_year"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE_TXT" => $request->post("location_data_forest_ad_tloc_fd_range_txt"),
							// "MAGROVE_PLANT_CRABS_HOLE" => $request->post("magrove_plant_crabs_hole"),
							// "REG_AVG_SEEDLING_PER_HA_ALL_PLOTS" => $request->post("reg_avg_seedling_per_ha_all_plots"),
							// "LOCATION_DATA_CA_UNION" => $request->post("location_data_ca_union"),
							// "SUBSCRIBERID" => $request->post("subscriberid"),
							// "GTRTS_PLANTING_PLANTING_YEAR_RAW" => $request->post("gtrts_planting_planting_year_raw"),
							// "GTRTS_OTHER_TREATMENT_OTHER_YEAR_RAW" => $request->post("gtrts_other_treatment_other_year_raw"),
							// "DEVICEID" => $request->post("deviceid"),
							// "PLANTING_PLAN_GENERATED_NOTE_NAME_151" => $request->post("planting_plan_generated_note_name_151"),
							// "INTERVENTION_DETAILS_TLOC_PLANT_YEAR" => $request->post("intervention_details_tloc_plant_year"),
							// "NURSERY_NURSERY_SITE_GENERATED_NOTE_NAME_179" => $request->post("nursery_nursery_site_generated_note_name_179"),
							// "INTERVENTION_DETAILS_TLOC_PLANT_TYPE" => $request->post("intervention_details_tloc_plant_type"),
							// "NURSERY_NUR_SITE_SELECTION_HILL_SAL_NUESERY_SUNLIGHT" => $request->post("nursery_nur_site_selection_hill_sal_nuesery_sunlight"),
							// "LOCATION_DATA_ECOZONE" => $request->post("location_data_ecozone"),
							// "GTRTS_PLANTATION_SITE_YEAR" => $request->post("gtrts_plantation_site_year"),
							// "GUSER_TUSER_CELL" => $request->post("guser_tuser_cell"),
							// "REG_AVG_TREES_PER_HA_ALL_PLOTS" => $request->post("reg_avg_trees_per_ha_all_plots"),
							// "NURSERY_NUR_SITE_SELECTION_HILL_SAL_NURSERY_AREA" => $request->post("nursery_nur_site_selection_hill_sal_nursery_area"),
							// "GTRTS_NUERSERY_RAISING_NURSERY_YEAR" => $request->post("gtrts_nuersery_raising_nursery_year"),
							// "GTRTS_CLIMBER_CUTTING_CLIMBER_YEAR" => $request->post("gtrts_climber_cutting_climber_year"),
							// "NURSERY_NURSERY_SITE_PSITEPOINT_NUR_ALT" => $request->post("nursery_nursery_site_psitepoint_nur_alt"),
							// "GTRTS_NUERSERY_RAISING_GENERATED_NOTE_NAME_221" => $request->post("gtrts_nuersery_raising_generated_note_name_221"),
							// "PLANTING_PLAN_SEEDLINGS_PER_HA" => $request->post("planting_plan_seedlings_per_ha"),
							// "GTRTS_COMPOST_COMPOST_YEAR_RAW" => $request->post("gtrts_compost_compost_year_raw"),
							// "NURSERY_NURSERY_SITE_NURSERY_LOCATION" => $request->post("nursery_nursery_site_nursery_location"),
							// "GSITE_LAND_COV_DESC" => $request->post("gsite_land_cov_desc"),
							// "SIMSERIAL" => $request->post("simserial"),
							// "GUSER_GENERATED_NOTE_NAME_13" => $request->post("guser_generated_note_name_13"),
							// "GUSER_DCOLLECTION_RAW" => $request->post("guser_dcollection_raw"),
							// "NURSERY_NURSERY_SITE_GCOORDS_NUR_SITE_EAST_NUR" => $request->post("nursery_nursery_site_gcoords_nur_site_east_nur"),
							// "GTRTS_OTHER_TREATMENT_OTHERS_SPECIFIED" => $request->post("gtrts_other_treatment_others_specified"),
							// "NURSERY_NUR_SITE_SELECTION_HILL_SAL_HIGH_LAND" => $request->post("nursery_nur_site_selection_hill_sal_high_land"),
							// "MAGROVE_PLANT_MAN_AFF_LEVEL_INUND" => $request->post("magrove_plant_man_aff_level_inund"),
							// "ALLPATCHES" => $request->post("allpatches"),
							// "GENERATED_NOTE_NAME_63" => $request->post("generated_note_name_63"),
							// "GUSER_TUSER_EMAIL" => $request->post("guser_tuser_email"),
							// "CHECKED_BY" => $request->post("checked_by"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_CIR" => $request->post("location_data_forest_ad_tloc_fd_cir"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_NURSERY_DIS2" => $request->post("nursery_nur_site_selection_coastal_area_nursery_dis2"),
							// "NURSERY_NURSERY_SITE_PSITEPOINT_NUR_LAT" => $request->post("nursery_nursery_site_psitepoint_nur_lat"),
							// "NURSERY_NUR_SITE_SELECTION_HILL_SAL_GENERATED_NOTE_NAME_190" => $request->post("nursery_nur_site_selection_hill_sal_generated_note_name_190"),
							// "LOCATION_DATA_TLOCATION" => $request->post("location_data_tlocation"),
							// "MAGROVE_PLANT_FACING_ISLAND" => $request->post("magrove_plant_facing_island"),
							// "GUSER_TUSER" => $request->post("guser_tuser"),
							// "MAGROVE_PLANT_MANGROVE_ENRICH_INUNDATION_MONTH" => $request->post("magrove_plant_mangrove_enrich_inundation_month"),
							// "NURSERY_OTHERS_INFO_CARETAKER_INFO_CARETAKER_NAME" => $request->post("nursery_others_info_caretaker_info_caretaker_name"),
							// "LOCATION_DATA_FOREST_AD_GENERATED_NOTE_NAME_23" => $request->post("location_data_forest_ad_generated_note_name_23"),
							// "GTRTS_NUERSERY_RAISING_NURSERY_YEAR_RAW" => $request->post("gtrts_nuersery_raising_nursery_year_raw"),
							// "NURSERY_NURSERY_SITE_PSITEPOINT_NUR_ACC" => $request->post("nursery_nursery_site_psitepoint_nur_acc"),
							// "GTRTS_PLANTATION_SITE_YEAR_RAW" => $request->post("gtrts_plantation_site_year_raw"),
							// "REGIN_NOTE_GENERATED_NOTE_NAME_115" => $request->post("regin_note_generated_note_name_115"),
							// "REGIN_NOTE_GENERATED_NOTE_NAME_114" => $request->post("regin_note_generated_note_name_114"),
							// "NURSERY_OTHERS_INFO_CARETAKER_INFO_CARETAKER_NID" => $request->post("nursery_others_info_caretaker_info_caretaker_nid"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_CHAR" => $request->post("location_data_forest_ad_tloc_fd_char"),
							// "GTRTS_OTHER_TREATMENT_GENERATED_NOTE_NAME_262" => $request->post("gtrts_other_treatment_generated_note_name_262"),
							// "REGIN_NOTE_GENERATED_NOTE_NAME_119" => $request->post("regin_note_generated_note_name_119"),
							// "REGIN_NOTE_GENERATED_NOTE_NAME_118" => $request->post("regin_note_generated_note_name_118"),
							// "REGIN_NOTE_GENERATED_NOTE_NAME_117" => $request->post("regin_note_generated_note_name_117"),
							// "REGIN_NOTE_GENERATED_NOTE_NAME_116" => $request->post("regin_note_generated_note_name_116"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_BLOCK" => $request->post("location_data_forest_ad_tloc_fd_block"),
							// "GTRTS_COMPOST_GENERATED_NOTE_NAME_247" => $request->post("gtrts_compost_generated_note_name_247"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_DIVISION" => $request->post("location_data_forest_ad_tloc_fd_division"),
							// "GTRTS_COMPOST_COMPOST_YEAR" => $request->post("gtrts_compost_compost_year"),
							// "GTRTS_PLANTING_GENERATED_NOTE_NAME_231" => $request->post("gtrts_planting_generated_note_name_231"),
							// "GUSER_DCOLLECTION" => $request->post("guser_dcollection"),
							// "CHECKED" => $request->post("checked"),
							// "GSITE_HIST_OTHER" => $request->post("gsite_hist_other"),
							// "MAGROVE_PLANT_MAN_AFF_GENERATED_NOTE_NAME_137" => $request->post("magrove_plant_man_aff_generated_note_name_137"),
							// "INTERVENTION_DETAILS_GENERATED_NOTE_NAME_122" => $request->post("intervention_details_generated_note_name_122"),
							// "MAGROVE_PLANT_MAN_AFF_GENERATED_NOTE_NAME_133" => $request->post("magrove_plant_man_aff_generated_note_name_133"),
							// "PLANTING_PLAN_TXT_BUILD1" => $request->post("planting_plan_txt_build1"),
							// "PLANTING_PLAN_TXT_BUILD2" => $request->post("planting_plan_txt_build2"),
							// "GTRTS_CLIMBER_CUTTING_GENERATED_NOTE_NAME_252" => $request->post("gtrts_climber_cutting_generated_note_name_252"),
							// "END_RAW" => $request->post("end_raw"),
							// "LOCATION_DATA_FOREST_AD_TLOC_ENTER_RANGE" => $request->post("location_data_forest_ad_tloc_enter_range"),
							// "NURSERY_NUR_SITE_SELECTION_HILL_SAL_NURSERY_DIS" => $request->post("nursery_nur_site_selection_hill_sal_nursery_dis"),
							// "PLANTING_PLAN_BPLANTING" => $request->post("planting_plan_bplanting"),
							// "NURSERY_NUR_SITE_SELECTION_HILL_SAL_DRAINAGE_FAC" => $request->post("nursery_nur_site_selection_hill_sal_drainage_fac"),
							// "LOCATION_DATA_CA_GENERATED_NOTE_NAME_36" => $request->post("location_data_ca_generated_note_name_36"),
							// "INTERVENTION_DETAILS_LLOC_PLANT_AREA" => $request->post("intervention_details_lloc_plant_area"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA1" => $request->post("nursery_nur_site_selection_coastal_area_coastal_area1"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA2" => $request->post("nursery_nur_site_selection_coastal_area_coastal_area2"),
							// "MAGROVE_PLANT_MANGROVE_ENRICH_GENERATED_NOTE_NAME_140" => $request->post("magrove_plant_mangrove_enrich_generated_note_name_140"),
							// "NURSERY_OTHERS_INFO_CARETAKER_INFO_CAREKATER_MOBILE" => $request->post("nursery_others_info_caretaker_info_carekater_mobile"),
							// "REG_PLOT_NO" => $request->post("reg_plot_no"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA7" => $request->post("nursery_nur_site_selection_coastal_area_coastal_area7"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA5" => $request->post("nursery_nur_site_selection_coastal_area_coastal_area5"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA6" => $request->post("nursery_nur_site_selection_coastal_area_coastal_area6"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA3" => $request->post("nursery_nur_site_selection_coastal_area_coastal_area3"),
							// "MAGROVE_PLANT_MANGROVE_ENRICH_PLANTATION_AGE" => $request->post("magrove_plant_mangrove_enrich_plantation_age"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA4" => $request->post("nursery_nur_site_selection_coastal_area_coastal_area4"),
							// "END" => $request->post("end"),
							// "PLANTING_PLAN_MAX_SEEDLINGS" => $request->post("planting_plan_max_seedlings"),
							// "PHONENUMBER" => $request->post("phonenumber"),
							// "GTRTS_PLANTATION_GENERATED_NOTE_NAME_226" => $request->post("gtrts_plantation_generated_note_name_226"),
							// "START_RAW" => $request->post("start_raw"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE" => $request->post("location_data_forest_ad_tloc_fd_range"),
							// "NURSERY_OTHERS_INFO_CARETAKER_INFO_GENERATED_NOTE_NAME_212" => $request->post("nursery_others_info_caretaker_info_generated_note_name_212"),
							// "META_INSTANCE_ID" => $request->post("meta_instance_id"),
							// "INTERVENTION_DETAILS_TLOC_PLANT_OTHERS" => $request->post("intervention_details_tloc_plant_others"),
							// "NURSERY_NURSERY_SITE_PSITEPOINT_NUR_LNG" => $request->post("nursery_nursery_site_psitepoint_nur_lng"),
							// "NURSERY_NURSERY_SITE_GCOORDS_NUR_SITE_NORTH_NUR" => $request->post("nursery_nursery_site_gcoords_nur_site_north_nur"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT" => $request->post("location_data_forest_ad_tloc_fd_beat"),
							// "MAGROVE_PLANT_FACING_DIR" => $request->post("magrove_plant_facing_dir"),
							// "NURSERY_NURSERY_SITE_TPOLYTYPE_NUR" => $request->post("nursery_nursery_site_tpolytype_nur"),
							// "LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT_TXT" => $request->post("location_data_forest_ad_tloc_fd_beat_txt"),
							// "MAGROVE_PLANT_MAN_AFF_PIONEERS_SP" => $request->post("magrove_plant_man_aff_pioneers_sp"),
							// "TODAY" => $request->post("today"),
							// "LOCATION_DATA_CA_TLOC_AD_DIVISION" => $request->post("location_data_ca_tloc_ad_division"),
							// "GTRTS_CLIMBER_CUTTING_CLIMBER_YEAR_RAW" => $request->post("gtrts_climber_cutting_climber_year_raw"),
							// "LOCATION_DATA_FOREST_AD_TLOC_ENTER_DIV" => $request->post("location_data_forest_ad_tloc_enter_div"),
							// "LOCATION_DATA_CA_VILLAGE" => $request->post("location_data_ca_village"),
							// "MAGROVE_PLANT_WAVE_DIR" => $request->post("magrove_plant_wave_dir"),
							// "NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_GENERATED_NOTE_NAME_199" => $request->post("nursery_nur_site_selection_coastal_area_generated_note_name_199"),
							// "GSITE_GENERATED_NOTE_NAME_72" => $request->post("gsite_generated_note_name_72"),
							// "NURSERY_NUR_SITE_SELECTION_HILL_SAL_WATER_SOURCE" => $request->post("nursery_nur_site_selection_hill_sal_water_source"),
							// "START" => $request->post("start"),
							// "REG_AVG_TREES_ALL_PLOTS" => $request->post("reg_avg_trees_all_plots"),
							// "TODAY_RAW" => $request->post("today_raw"),
							// "APPROVED" => $request->post("approved"),
							// "MAGROVE_PLANT_GENERATED_NOTE_NAME_131" => $request->post("magrove_plant_generated_note_name_131"),
							// "project_id" => $request->post("project_id"),
							// "sort" => $request->post("sort"),
							// "last_log_id" => $request->post("last_log_id"),
							// "restore_id" => $request->post("restore_id"),
							// "created_at" => $request->post("created_at"),
							// "created_by" => $request->post("created_by"),
							// "updated_at" => $request->post("updated_at"),
							// "updated_by" => $request->post("updated_by"),
							// "deleted_at" => $request->post("deleted_at"),
							// "deleted_by" => $request->post("deleted_by"),
							// "deleted_status" => $request->post("deleted_status"),
							// "status" => $request->post("status"),

			);
			$insert_id = DB::table("aggregate.PLANT27_2021_CORE")->insert($data);
			return response()->json($insert_id);
		}
		public function plant27_2021_core_list($id,$id2,$id3,$id4){
			DB::EnableQueryLog();
            $sql = "
            select
                
                plant.\"_URI\",
                plant.\"GUSER_DCOLLECTION_RAW\",
                plant.\"INTERVENTION_DETAILS_LLOC_PLANT_AREA\",
                fy.\"name\" as INTERVENTION_DETAILS_TLOC_PLANT_YEAR,
                il.\"name\" as INTERVENTION_DETAILS_TLOC_PLANT_TYPE,
                jfb.\"name\" as LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT, 
                jfc.\"name\"  as LOCATION_DATA_FOREST_AD_TLOC_FD_CIR,
                jfd.\"name\" as LOCATION_DATA_FOREST_AD_TLOC_FD_DIVISION,
                jfr.\"name\" as LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE
                from aggregate.\"PLANT27_2021_CORE\" as plant
                left join jur_fd_beats jfb on jfb.code=plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT\"
                left join jur_fd_circles jfc on jfc.code=plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_CIR\"
                left join jur_fd_divisions jfd on jfd.code=plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_DIVISION\"
                left join jur_fd_ranges jfr on jfr.code=plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE\"
                left join financial_years fy on fy.code=plant.\"INTERVENTION_DETAILS_TLOC_PLANT_YEAR\"
                left join intervention_lists il on il.code=plant.\"INTERVENTION_DETAILS_TLOC_PLANT_TYPE\"
                where  plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_CIR\" = '$id' and plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_DIVISION\" = '$id2' and 
                plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE\" = '$id3' and plant.\"LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT\" = '$id4'
            ";
            $query =  DB::select($sql);
            $q=DB::GetQueryLog();
            return response()->json($query);
			
		}
	}
			