<?php
	namespace App\Http\Controllers\Api\Aggregate;

	use App\Http\Controllers\Controller;
	use DB;

	class Plant27_2021_core_test extends Controller
	{
		
		public function plant27_2021_core_test_create(){
			$data = array(
				"_URI" => Request::input("_uri"),
"_CREATOR_URI_USER" => Request::input("_creator_uri_user"),
"_CREATION_DATE" => Request::input("_creation_date"),
"_LAST_UPDATE_URI_USER" => Request::input("_last_update_uri_user"),
"_LAST_UPDATE_DATE" => Request::input("_last_update_date"),
"_MODEL_VERSION" => Request::input("_model_version"),
"_UI_VERSION" => Request::input("_ui_version"),
"_IS_COMPLETE" => Request::input("_is_complete"),
"_SUBMISSION_DATE" => Request::input("_submission_date"),
"_MARKED_AS_COMPLETE_DATE" => Request::input("_marked_as_complete_date"),
"PLANTING_PLAN_SEEDLING_NUM_GENERATED_NOTE_NAME_173" => Request::input("planting_plan_seedling_num_generated_note_name_173"),
"REG_AVG_SEEDLING_ALL_PLOTS" => Request::input("reg_avg_seedling_all_plots"),
"PLANTING_PLAN_GRPSTOCKS_NTE_1" => Request::input("planting_plan_grpstocks_nte_1"),
"PLANTING_PLAN_GRPSTOCKS_NTE_2" => Request::input("planting_plan_grpstocks_nte_2"),
"PLANTING_PLAN_SEEDLING_NUM_GENERATED_NOTE_NAME_174" => Request::input("planting_plan_seedling_num_generated_note_name_174"),
"LOCATION_DATA_CA_TLOC_AD_DISTRICT" => Request::input("location_data_ca_tloc_ad_district"),
"MAGROVE_PLANT_WIND_DIR" => Request::input("magrove_plant_wind_dir"),
"GSITE_HISTORY" => Request::input("gsite_history"),
"LOCATION_DATA_GENERATED_NOTE_NAME_20" => Request::input("location_data_generated_note_name_20"),
"GTRTS_PLANTING_PLANTING_YEAR" => Request::input("gtrts_planting_planting_year"),
"INTERVENTION_DETAILS_PATCHES_PLANT" => Request::input("intervention_details_patches_plant"),
"INTERVENTION_DETAILS_SEEDING_PLANT" => Request::input("intervention_details_seeding_plant"),
"PLANTING_PLAN_GPLANTING_SPACING" => Request::input("planting_plan_gplanting_spacing"),
"MAGROVE_PLANT_MAN_AFF_CLAY_LAYER" => Request::input("magrove_plant_man_aff_clay_layer"),
"GTRTS_OTHER_TREATMENT_OTHER_YEAR" => Request::input("gtrts_other_treatment_other_year"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE_TXT" => Request::input("location_data_forest_ad_tloc_fd_range_txt"),
"MAGROVE_PLANT_CRABS_HOLE" => Request::input("magrove_plant_crabs_hole"),
"REG_AVG_SEEDLING_PER_HA_ALL_PLOTS" => Request::input("reg_avg_seedling_per_ha_all_plots"),
"LOCATION_DATA_CA_UNION" => Request::input("location_data_ca_union"),
"SUBSCRIBERID" => Request::input("subscriberid"),
"GTRTS_PLANTING_PLANTING_YEAR_RAW" => Request::input("gtrts_planting_planting_year_raw"),
"GTRTS_OTHER_TREATMENT_OTHER_YEAR_RAW" => Request::input("gtrts_other_treatment_other_year_raw"),
"DEVICEID" => Request::input("deviceid"),
"PLANTING_PLAN_GENERATED_NOTE_NAME_151" => Request::input("planting_plan_generated_note_name_151"),
"INTERVENTION_DETAILS_TLOC_PLANT_YEAR" => Request::input("intervention_details_tloc_plant_year"),
"NURSERY_NURSERY_SITE_GENERATED_NOTE_NAME_179" => Request::input("nursery_nursery_site_generated_note_name_179"),
"INTERVENTION_DETAILS_TLOC_PLANT_TYPE" => Request::input("intervention_details_tloc_plant_type"),
"NURSERY_NUR_SITE_SELECTION_HILL_SAL_NUESERY_SUNLIGHT" => Request::input("nursery_nur_site_selection_hill_sal_nuesery_sunlight"),
"LOCATION_DATA_ECOZONE" => Request::input("location_data_ecozone"),
"GTRTS_PLANTATION_SITE_YEAR" => Request::input("gtrts_plantation_site_year"),
"GUSER_TUSER_CELL" => Request::input("guser_tuser_cell"),
"REG_AVG_TREES_PER_HA_ALL_PLOTS" => Request::input("reg_avg_trees_per_ha_all_plots"),
"NURSERY_NUR_SITE_SELECTION_HILL_SAL_NURSERY_AREA" => Request::input("nursery_nur_site_selection_hill_sal_nursery_area"),
"GTRTS_NUERSERY_RAISING_NURSERY_YEAR" => Request::input("gtrts_nuersery_raising_nursery_year"),
"GTRTS_CLIMBER_CUTTING_CLIMBER_YEAR" => Request::input("gtrts_climber_cutting_climber_year"),
"NURSERY_NURSERY_SITE_PSITEPOINT_NUR_ALT" => Request::input("nursery_nursery_site_psitepoint_nur_alt"),
"GTRTS_NUERSERY_RAISING_GENERATED_NOTE_NAME_221" => Request::input("gtrts_nuersery_raising_generated_note_name_221"),
"PLANTING_PLAN_SEEDLINGS_PER_HA" => Request::input("planting_plan_seedlings_per_ha"),
"GTRTS_COMPOST_COMPOST_YEAR_RAW" => Request::input("gtrts_compost_compost_year_raw"),
"NURSERY_NURSERY_SITE_NURSERY_LOCATION" => Request::input("nursery_nursery_site_nursery_location"),
"GSITE_LAND_COV_DESC" => Request::input("gsite_land_cov_desc"),
"SIMSERIAL" => Request::input("simserial"),
"GUSER_GENERATED_NOTE_NAME_13" => Request::input("guser_generated_note_name_13"),
"GUSER_DCOLLECTION_RAW" => Request::input("guser_dcollection_raw"),
"NURSERY_NURSERY_SITE_GCOORDS_NUR_SITE_EAST_NUR" => Request::input("nursery_nursery_site_gcoords_nur_site_east_nur"),
"GTRTS_OTHER_TREATMENT_OTHERS_SPECIFIED" => Request::input("gtrts_other_treatment_others_specified"),
"NURSERY_NUR_SITE_SELECTION_HILL_SAL_HIGH_LAND" => Request::input("nursery_nur_site_selection_hill_sal_high_land"),
"MAGROVE_PLANT_MAN_AFF_LEVEL_INUND" => Request::input("magrove_plant_man_aff_level_inund"),
"ALLPATCHES" => Request::input("allpatches"),
"GENERATED_NOTE_NAME_63" => Request::input("generated_note_name_63"),
"GUSER_TUSER_EMAIL" => Request::input("guser_tuser_email"),
"CHECKED_BY" => Request::input("checked_by"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_CIR" => Request::input("location_data_forest_ad_tloc_fd_cir"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_NURSERY_DIS2" => Request::input("nursery_nur_site_selection_coastal_area_nursery_dis2"),
"NURSERY_NURSERY_SITE_PSITEPOINT_NUR_LAT" => Request::input("nursery_nursery_site_psitepoint_nur_lat"),
"NURSERY_NUR_SITE_SELECTION_HILL_SAL_GENERATED_NOTE_NAME_190" => Request::input("nursery_nur_site_selection_hill_sal_generated_note_name_190"),
"LOCATION_DATA_TLOCATION" => Request::input("location_data_tlocation"),
"MAGROVE_PLANT_FACING_ISLAND" => Request::input("magrove_plant_facing_island"),
"GUSER_TUSER" => Request::input("guser_tuser"),
"MAGROVE_PLANT_MANGROVE_ENRICH_INUNDATION_MONTH" => Request::input("magrove_plant_mangrove_enrich_inundation_month"),
"NURSERY_OTHERS_INFO_CARETAKER_INFO_CARETAKER_NAME" => Request::input("nursery_others_info_caretaker_info_caretaker_name"),
"LOCATION_DATA_FOREST_AD_GENERATED_NOTE_NAME_23" => Request::input("location_data_forest_ad_generated_note_name_23"),
"GTRTS_NUERSERY_RAISING_NURSERY_YEAR_RAW" => Request::input("gtrts_nuersery_raising_nursery_year_raw"),
"NURSERY_NURSERY_SITE_PSITEPOINT_NUR_ACC" => Request::input("nursery_nursery_site_psitepoint_nur_acc"),
"GTRTS_PLANTATION_SITE_YEAR_RAW" => Request::input("gtrts_plantation_site_year_raw"),
"REGIN_NOTE_GENERATED_NOTE_NAME_115" => Request::input("regin_note_generated_note_name_115"),
"REGIN_NOTE_GENERATED_NOTE_NAME_114" => Request::input("regin_note_generated_note_name_114"),
"NURSERY_OTHERS_INFO_CARETAKER_INFO_CARETAKER_NID" => Request::input("nursery_others_info_caretaker_info_caretaker_nid"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_CHAR" => Request::input("location_data_forest_ad_tloc_fd_char"),
"GTRTS_OTHER_TREATMENT_GENERATED_NOTE_NAME_262" => Request::input("gtrts_other_treatment_generated_note_name_262"),
"REGIN_NOTE_GENERATED_NOTE_NAME_119" => Request::input("regin_note_generated_note_name_119"),
"REGIN_NOTE_GENERATED_NOTE_NAME_118" => Request::input("regin_note_generated_note_name_118"),
"REGIN_NOTE_GENERATED_NOTE_NAME_117" => Request::input("regin_note_generated_note_name_117"),
"REGIN_NOTE_GENERATED_NOTE_NAME_116" => Request::input("regin_note_generated_note_name_116"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_BLOCK" => Request::input("location_data_forest_ad_tloc_fd_block"),
"GTRTS_COMPOST_GENERATED_NOTE_NAME_247" => Request::input("gtrts_compost_generated_note_name_247"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_DIVISION" => Request::input("location_data_forest_ad_tloc_fd_division"),
"GTRTS_COMPOST_COMPOST_YEAR" => Request::input("gtrts_compost_compost_year"),
"GTRTS_PLANTING_GENERATED_NOTE_NAME_231" => Request::input("gtrts_planting_generated_note_name_231"),
"GUSER_DCOLLECTION" => Request::input("guser_dcollection"),
"CHECKED" => Request::input("checked"),
"GSITE_HIST_OTHER" => Request::input("gsite_hist_other"),
"MAGROVE_PLANT_MAN_AFF_GENERATED_NOTE_NAME_137" => Request::input("magrove_plant_man_aff_generated_note_name_137"),
"INTERVENTION_DETAILS_GENERATED_NOTE_NAME_122" => Request::input("intervention_details_generated_note_name_122"),
"MAGROVE_PLANT_MAN_AFF_GENERATED_NOTE_NAME_133" => Request::input("magrove_plant_man_aff_generated_note_name_133"),
"PLANTING_PLAN_TXT_BUILD1" => Request::input("planting_plan_txt_build1"),
"PLANTING_PLAN_TXT_BUILD2" => Request::input("planting_plan_txt_build2"),
"GTRTS_CLIMBER_CUTTING_GENERATED_NOTE_NAME_252" => Request::input("gtrts_climber_cutting_generated_note_name_252"),
"END_RAW" => Request::input("end_raw"),
"LOCATION_DATA_FOREST_AD_TLOC_ENTER_RANGE" => Request::input("location_data_forest_ad_tloc_enter_range"),
"NURSERY_NUR_SITE_SELECTION_HILL_SAL_NURSERY_DIS" => Request::input("nursery_nur_site_selection_hill_sal_nursery_dis"),
"PLANTING_PLAN_BPLANTING" => Request::input("planting_plan_bplanting"),
"NURSERY_NUR_SITE_SELECTION_HILL_SAL_DRAINAGE_FAC" => Request::input("nursery_nur_site_selection_hill_sal_drainage_fac"),
"LOCATION_DATA_CA_GENERATED_NOTE_NAME_36" => Request::input("location_data_ca_generated_note_name_36"),
"INTERVENTION_DETAILS_LLOC_PLANT_AREA" => Request::input("intervention_details_lloc_plant_area"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA1" => Request::input("nursery_nur_site_selection_coastal_area_coastal_area1"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA2" => Request::input("nursery_nur_site_selection_coastal_area_coastal_area2"),
"MAGROVE_PLANT_MANGROVE_ENRICH_GENERATED_NOTE_NAME_140" => Request::input("magrove_plant_mangrove_enrich_generated_note_name_140"),
"NURSERY_OTHERS_INFO_CARETAKER_INFO_CAREKATER_MOBILE" => Request::input("nursery_others_info_caretaker_info_carekater_mobile"),
"REG_PLOT_NO" => Request::input("reg_plot_no"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA7" => Request::input("nursery_nur_site_selection_coastal_area_coastal_area7"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA5" => Request::input("nursery_nur_site_selection_coastal_area_coastal_area5"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA6" => Request::input("nursery_nur_site_selection_coastal_area_coastal_area6"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA3" => Request::input("nursery_nur_site_selection_coastal_area_coastal_area3"),
"MAGROVE_PLANT_MANGROVE_ENRICH_PLANTATION_AGE" => Request::input("magrove_plant_mangrove_enrich_plantation_age"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_COASTAL_AREA4" => Request::input("nursery_nur_site_selection_coastal_area_coastal_area4"),
"END" => Request::input("end"),
"PLANTING_PLAN_MAX_SEEDLINGS" => Request::input("planting_plan_max_seedlings"),
"PHONENUMBER" => Request::input("phonenumber"),
"GTRTS_PLANTATION_GENERATED_NOTE_NAME_226" => Request::input("gtrts_plantation_generated_note_name_226"),
"START_RAW" => Request::input("start_raw"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE" => Request::input("location_data_forest_ad_tloc_fd_range"),
"NURSERY_OTHERS_INFO_CARETAKER_INFO_GENERATED_NOTE_NAME_212" => Request::input("nursery_others_info_caretaker_info_generated_note_name_212"),
"META_INSTANCE_ID" => Request::input("meta_instance_id"),
"INTERVENTION_DETAILS_TLOC_PLANT_OTHERS" => Request::input("intervention_details_tloc_plant_others"),
"NURSERY_NURSERY_SITE_PSITEPOINT_NUR_LNG" => Request::input("nursery_nursery_site_psitepoint_nur_lng"),
"NURSERY_NURSERY_SITE_GCOORDS_NUR_SITE_NORTH_NUR" => Request::input("nursery_nursery_site_gcoords_nur_site_north_nur"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT" => Request::input("location_data_forest_ad_tloc_fd_beat"),
"MAGROVE_PLANT_FACING_DIR" => Request::input("magrove_plant_facing_dir"),
"NURSERY_NURSERY_SITE_TPOLYTYPE_NUR" => Request::input("nursery_nursery_site_tpolytype_nur"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT_TXT" => Request::input("location_data_forest_ad_tloc_fd_beat_txt"),
"MAGROVE_PLANT_MAN_AFF_PIONEERS_SP" => Request::input("magrove_plant_man_aff_pioneers_sp"),
"TODAY" => Request::input("today"),
"LOCATION_DATA_CA_TLOC_AD_DIVISION" => Request::input("location_data_ca_tloc_ad_division"),
"GTRTS_CLIMBER_CUTTING_CLIMBER_YEAR_RAW" => Request::input("gtrts_climber_cutting_climber_year_raw"),
"LOCATION_DATA_FOREST_AD_TLOC_ENTER_DIV" => Request::input("location_data_forest_ad_tloc_enter_div"),
"LOCATION_DATA_CA_VILLAGE" => Request::input("location_data_ca_village"),
"MAGROVE_PLANT_WAVE_DIR" => Request::input("magrove_plant_wave_dir"),
"NURSERY_NUR_SITE_SELECTION_COASTAL_AREA_GENERATED_NOTE_NAME_199" => Request::input("nursery_nur_site_selection_coastal_area_generated_note_name_199"),
"GSITE_GENERATED_NOTE_NAME_72" => Request::input("gsite_generated_note_name_72"),
"NURSERY_NUR_SITE_SELECTION_HILL_SAL_WATER_SOURCE" => Request::input("nursery_nur_site_selection_hill_sal_water_source"),
"START" => Request::input("start"),
"REG_AVG_TREES_ALL_PLOTS" => Request::input("reg_avg_trees_all_plots"),
"TODAY_RAW" => Request::input("today_raw"),
"APPROVED" => Request::input("approved"),
"MAGROVE_PLANT_GENERATED_NOTE_NAME_131" => Request::input("magrove_plant_generated_note_name_131"),
"project_id" => Request::input("project_id"),
"sort" => Request::input("sort"),
"last_log_id" => Request::input("last_log_id"),
"restore_id" => Request::input("restore_id"),
"created_at" => Request::input("created_at"),
"created_by" => Request::input("created_by"),
"updated_at" => Request::input("updated_at"),
"updated_by" => Request::input("updated_by"),
"deleted_at" => Request::input("deleted_at"),
"deleted_by" => Request::input("deleted_by"),
"deleted_status" => Request::input("deleted_status"),
"status" => Request::input("status"),

			);
			$insert_id = DB::table("PLANT27_2021_CORE_TEST")->insertGetId($data);
			return response()->json($insert_id);
		}
		public function plant27_2021_core_test_list(){
			$query = DB::select('select * from aggregate."PLANT27_2021_CORE_TEST"');
			return response()->json($query);
		}
	}
			