<?php
	namespace App\Http\Controllers\Api\Aggregate;

	use App\Http\Controllers\Controller;
	use DB;

	class Sufal192020_core extends Controller
	{
		
		public function sufal192020_core_create(){
			$data = array(
				"_URI" => Request::input("_uri"),
"_CREATOR_URI_USER" => Request::input("_creator_uri_user"),
"_CREATION_DATE" => Request::input("_creation_date"),
"_LAST_UPDATE_URI_USER" => Request::input("_last_update_uri_user"),
"_LAST_UPDATE_DATE" => Request::input("_last_update_date"),
"_MODEL_VERSION" => Request::input("_model_version"),
"_UI_VERSION" => Request::input("_ui_version"),
"_IS_COMPLETE" => Request::input("_is_complete"),
"_SUBMISSION_DATE" => Request::input("_submission_date"),
"_MARKED_AS_COMPLETE_DATE" => Request::input("_marked_as_complete_date"),
"REG_AVG_SEEDLING_ALL_PLOTS" => Request::input("reg_avg_seedling_all_plots"),
"GTRTS_COMMUNITY_PROTECTION_COMMUNITY_YEAR" => Request::input("gtrts_community_protection_community_year"),
"PLANTING_PLAN_GPLANTING_GNURSERY_GCOORDS_NUR_NAME_CAR" => Request::input("planting_plan_gplanting_gnursery_gcoords_nur_name_car"),
"PLANTING_PLAN_GPLANTING_BNURSERY" => Request::input("planting_plan_gplanting_bnursery"),
"LOCATION_DATA_CA_TLOC_AD_DISTRICT" => Request::input("location_data_ca_tloc_ad_district"),
"GUSER_SURVEY_TYPE" => Request::input("guser_survey_type"),
"GTRTS_LAYOUT_LAYOUT_YEAR_RAW" => Request::input("gtrts_layout_layout_year_raw"),
"GTRTS_PLANTING_PLANTING_YEAR" => Request::input("gtrts_planting_planting_year"),
"MAN_AFF_CLAY_LAYER" => Request::input("man_aff_clay_layer"),
"GUSER_REASON_4_CHANGE" => Request::input("guser_reason_4_change"),
"GTRTS_COMPOSTS_PIT_COMPOSTS_PIT_YEAR_RAW" => Request::input("gtrts_composts_pit_composts_pit_year_raw"),
"PLANTING_PLAN_GPLANTING_SPACING" => Request::input("planting_plan_gplanting_spacing"),
"PLANTING_PLAN_GPLANTING_GNURSERY_PSITEPOINT_NUR_LAT" => Request::input("planting_plan_gplanting_gnursery_psitepoint_nur_lat"),
"REGIN_NOTE_GENERATED_NOTE_NAME_107" => Request::input("regin_note_generated_note_name_107"),
"REGIN_NOTE_GENERATED_NOTE_NAME_106" => Request::input("regin_note_generated_note_name_106"),
"REGIN_NOTE_GENERATED_NOTE_NAME_105" => Request::input("regin_note_generated_note_name_105"),
"INTERVENTION_DETAILS_TYPE_PLANT_TLOC_PLANT_OTHERS" => Request::input("intervention_details_type_plant_tloc_plant_others"),
"GTRTS_OTHER_TREATMENT_OTHER_YEAR" => Request::input("gtrts_other_treatment_other_year"),
"PLANTING_PLAN_GPLANTING_GNURSERY_NURSERY_ESTAB" => Request::input("planting_plan_gplanting_gnursery_nursery_estab"),
"REG_AVG_SEEDLING_PER_HA_ALL_PLOTS" => Request::input("reg_avg_seedling_per_ha_all_plots"),
"LOCATION_DATA_CA_UNION" => Request::input("location_data_ca_union"),
"SUBSCRIBERID" => Request::input("subscriberid"),
"PLANTING_PLAN_GPLANTING_GNURSERY_GCOORDS_NUR_NUR_CAR_MO_NO" => Request::input("planting_plan_gplanting_gnursery_gcoords_nur_nur_car_mo_no"),
"GUSER_PREVIOUS_RECORD" => Request::input("guser_previous_record"),
"GTRTS_PLANTING_PLANTING_YEAR_RAW" => Request::input("gtrts_planting_planting_year_raw"),
"PLANTING_PLAN_GPLANTING_GNURSERY_NURS_NOTES" => Request::input("planting_plan_gplanting_gnursery_nurs_notes"),
"GTRTS_OTHER_TREATMENT_OTHER_YEAR_RAW" => Request::input("gtrts_other_treatment_other_year_raw"),
"DEVICEID" => Request::input("deviceid"),
"INTERVENTION_DETAILS_TLOC_PLANT_YEAR" => Request::input("intervention_details_tloc_plant_year"),
"PLANTING_PLAN_GPLANTING_GNURSERY_TOTNURSEEDLINGS" => Request::input("planting_plan_gplanting_gnursery_totnurseedlings"),
"GTRTS_PLANTATION_SITE_YEAR" => Request::input("gtrts_plantation_site_year"),
"GUSER_TUSER_CELL" => Request::input("guser_tuser_cell"),
"PLANTING_PLAN_GPLANTING_GNURSERY_PSITEPOINT_NUR_ACC" => Request::input("planting_plan_gplanting_gnursery_psitepoint_nur_acc"),
"PLANTING_PLAN_GPLANTING_SEEDLING_NUM_GENERATED_NOTE_NAME_152" => Request::input("planting_plan_gplanting_seedling_num_generated_note_name_152"),
"PLANTING_PLAN_GPLANTING_SEEDLING_NUM_GENERATED_NOTE_NAME_151" => Request::input("planting_plan_gplanting_seedling_num_generated_note_name_151"),
"MAN_AFF_WIND_DIR" => Request::input("man_aff_wind_dir"),
"GTRTS_NUERSERY_RAISING_NURSERY_YEAR" => Request::input("gtrts_nuersery_raising_nursery_year"),
"GTRTS_CLIMBER_CUTTING_CLIMBER_YEAR" => Request::input("gtrts_climber_cutting_climber_year"),
"PLANTING_PLAN_GPLANTING_GNURSERY_GCOORDS_NUR_SITE_EAST_NUR" => Request::input("planting_plan_gplanting_gnursery_gcoords_nur_site_east_nur"),
"PLANTING_PLAN_GPLANTING_GNURSERY_NURSERY_ESTAB_RAW" => Request::input("planting_plan_gplanting_gnursery_nursery_estab_raw"),
"GTRTS_COMPOST_COMPOST_YEAR_RAW" => Request::input("gtrts_compost_compost_year_raw"),
"SIMSERIAL" => Request::input("simserial"),
"MAN_AFF_WAVE_DIR" => Request::input("man_aff_wave_dir"),
"GUSER_DCOLLECTION_RAW" => Request::input("guser_dcollection_raw"),
"PLANTING_PLAN_GPLANTING_MAX_SEEDLINGS" => Request::input("planting_plan_gplanting_max_seedlings"),
"GTRTS_OTHER_TREATMENT_OTHERS_SPECIFIED" => Request::input("gtrts_other_treatment_others_specified"),
"GTRTS_COMPOSTS_PIT_COMPOSTS_PIT_YEAR" => Request::input("gtrts_composts_pit_composts_pit_year"),
"ALLPATCHES" => Request::input("allpatches"),
"GSITE_ECOLOGICAL_ATTRIBUTES_SF_PROG" => Request::input("gsite_ecological_attributes_sf_prog"),
"CHECKED_BY" => Request::input("checked_by"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_CIR" => Request::input("location_data_forest_ad_tloc_fd_cir"),
"GENERATED_NOTE_NAME_62" => Request::input("generated_note_name_62"),
"GSITE_ECOLOGICAL_ATTRIBUTES_HIST_OTHER" => Request::input("gsite_ecological_attributes_hist_other"),
"MAN_AFF_FACING_ISLAND" => Request::input("man_aff_facing_island"),
"LOCATION_DATA_TLOCATION" => Request::input("location_data_tlocation"),
"GUSER_TUSER" => Request::input("guser_tuser"),
"PLANTING_PLAN_GPLANTING_GNURSERY_SEEDLING_SUM" => Request::input("planting_plan_gplanting_gnursery_seedling_sum"),
"GTRTS_NUERSERY_RAISING_NURSERY_YEAR_RAW" => Request::input("gtrts_nuersery_raising_nursery_year_raw"),
"INTERVENTION_DETAILS_TYPE_PLANT_PATCHES_PLANT" => Request::input("intervention_details_type_plant_patches_plant"),
"INTERVENTION_DETAILS_TYPE_PLANT_TLOC_PLANT_TYPE" => Request::input("intervention_details_type_plant_tloc_plant_type"),
"GTRTS_PLANTATION_SITE_YEAR_RAW" => Request::input("gtrts_plantation_site_year_raw"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_CHAR" => Request::input("location_data_forest_ad_tloc_fd_char"),
"ECOZONE" => Request::input("ecozone"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_BLOCK" => Request::input("location_data_forest_ad_tloc_fd_block"),
"PLANTING_PLAN_GPLANTING_GNURSERY_GCOORDS_NUR_SITE_NORTH_NUR" => Request::input("planting_plan_gplanting_gnursery_gcoords_nur_site_north_nur"),
"REGIN_NOTE_REGEN_NOTES" => Request::input("regin_note_regen_notes"),
"MAN_AFF_PIONEERS_SP" => Request::input("man_aff_pioneers_sp"),
"GTRTS_CLEANING_CUTTING_CUTTING_YEAR" => Request::input("gtrts_cleaning_cutting_cutting_year"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_DIVISION" => Request::input("location_data_forest_ad_tloc_fd_division"),
"GTRTS_COMPOST_COMPOST_YEAR" => Request::input("gtrts_compost_compost_year"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_CAMP" => Request::input("location_data_forest_ad_tloc_fd_camp"),
"GUSER_DCOLLECTION" => Request::input("guser_dcollection"),
"CHECKED" => Request::input("checked"),
"GTRTS_CLEANING_CUTTING_CUTTING_YEAR_RAW" => Request::input("gtrts_cleaning_cutting_cutting_year_raw"),
"GTRTS_PIT_DIGGING_DIGGING_YEAR" => Request::input("gtrts_pit_digging_digging_year"),
"END_RAW" => Request::input("end_raw"),
"LOCATION_DATA_FOREST_AD_TLOC_ENTER_RANGE" => Request::input("location_data_forest_ad_tloc_enter_range"),
"OVERALLNOTES" => Request::input("overallnotes"),
"INTERVENTION_DETAILS_TYPE_PLANT_AREA_ACIVITY" => Request::input("intervention_details_type_plant_area_acivity"),
"GTRTS_VACANCY_FILLING_FILLING_YEAR_RAW" => Request::input("gtrts_vacancy_filling_filling_year_raw"),
"PLANTING_PLAN_BPLANTING" => Request::input("planting_plan_bplanting"),
"PLANTING_PLAN_GPLANTING_GNURSERY_PSITEPOINT_NUR_LNG" => Request::input("planting_plan_gplanting_gnursery_psitepoint_nur_lng"),
"GTRTS_LAYOUT_LAYOUT_YEAR" => Request::input("gtrts_layout_layout_year"),
"INTERVENTION_DETAILS_LLOC_PLANT_AREA" => Request::input("intervention_details_lloc_plant_area"),
"TINTERVENTION" => Request::input("tintervention"),
"REG_PLOT_NO" => Request::input("reg_plot_no"),
"PLANTING_PLAN_GPLANTING_GRPSTOCKS_NTE_2" => Request::input("planting_plan_gplanting_grpstocks_nte_2"),
"END" => Request::input("end"),
"PLANTING_PLAN_GPLANTING_GRPSTOCKS_NTE_1" => Request::input("planting_plan_gplanting_grpstocks_nte_1"),
"PLANTING_PLAN_GPLANTING_GNURSERY_TPOLYTYPE_NUR" => Request::input("planting_plan_gplanting_gnursery_tpolytype_nur"),
"INTERVENTION_DETAILS_TYPE_PLANT_SEEDING_PLANT" => Request::input("intervention_details_type_plant_seeding_plant"),
"PHONENUMBER" => Request::input("phonenumber"),
"MAN_AFF_FACING_DIR" => Request::input("man_aff_facing_dir"),
"GSITE_ECOLOGICAL_ATTRIBUTES_LAND_COV_DESC" => Request::input("gsite_ecological_attributes_land_cov_desc"),
"START_RAW" => Request::input("start_raw"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_RANGE" => Request::input("location_data_forest_ad_tloc_fd_range"),
"GTRTS_VACANCY_FILLING_FILLING_YEAR" => Request::input("gtrts_vacancy_filling_filling_year"),
"META_INSTANCE_ID" => Request::input("meta_instance_id"),
"PLANTING_PLAN_GPLANTING_SEEDLINGS_PER_HA" => Request::input("planting_plan_gplanting_seedlings_per_ha"),
"GSITE_ECOLOGICAL_ATTRIBUTES_TLANDCOVERCLASS" => Request::input("gsite_ecological_attributes_tlandcoverclass"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT" => Request::input("location_data_forest_ad_tloc_fd_beat"),
"PLANTING_PLAN_GPLANTING_GNURSERY_GCOORDS_NUR_NUR_CAR_NID" => Request::input("planting_plan_gplanting_gnursery_gcoords_nur_nur_car_nid"),
"PLANTING_PLAN_GPLANTING_TXT_BUILD2" => Request::input("planting_plan_gplanting_txt_build2"),
"PLANTING_PLAN_GPLANTING_GNURSERY_PSITEPOINT_NUR_ALT" => Request::input("planting_plan_gplanting_gnursery_psitepoint_nur_alt"),
"LOCATION_DATA_FOREST_AD_TLOC_FD_BEAT_TXT" => Request::input("location_data_forest_ad_tloc_fd_beat_txt"),
"GSITE_ECOLOGICAL_ATTRIBUTES_HISTORY" => Request::input("gsite_ecological_attributes_history"),
"PLANTING_PLAN_GPLANTING_TXT_BUILD1" => Request::input("planting_plan_gplanting_txt_build1"),
"TODAY" => Request::input("today"),
"LOCATION_DATA_CA_TLOC_AD_DIVISION" => Request::input("location_data_ca_tloc_ad_division"),
"GTRTS_CLIMBER_CUTTING_CLIMBER_YEAR_RAW" => Request::input("gtrts_climber_cutting_climber_year_raw"),
"LOCATION_DATA_FOREST_AD_TLOC_ENTER_DIV" => Request::input("location_data_forest_ad_tloc_enter_div"),
"PLANTING_PLAN_GPLANTING_DAREA_PLANTING" => Request::input("planting_plan_gplanting_darea_planting"),
"GTRTS_COMMUNITY_PROTECTION_COMMUNITY_YEAR_RAW" => Request::input("gtrts_community_protection_community_year_raw"),
"START" => Request::input("start"),
"GTRTS_PIT_DIGGING_DIGGING_YEAR_RAW" => Request::input("gtrts_pit_digging_digging_year_raw"),
"TODAY_RAW" => Request::input("today_raw"),
"APPROVED" => Request::input("approved"),

			);
			$insert_id = DB::table("SUFAL192020_CORE")->insertGetId($data);
			return response()->json($insert_id);
		}
		public function sufal192020_core_list(){
			$query = DB::select('select * from aggregate."SUFAL192020_CORE"');
			return response()->json($query);
		}
	}
			